### ISSUE TITLE
Information about Linux and Coding department 

### ISSUE THREAD

**Issue by chiragw15** [Njack-Website/Njack-Website#3]
Someone please add this. @KokareIITP let me know if changes are required.
Coding Department:

The **CODING** Department of NJACK is the department for Competitive Programming enthusiasts. The group mainly focuses on Algorithms and Data Structures. We conduct sessions and workshops, hold lectures and talks, and even host coding competitions. The main competition conducted by the department is Byterace. Whether you want to learn, do well on online judges like Codechef, Codeforces and Topcoder, prepare for competitions like Google Code Jam, Facebook HackerCup and the ACM-ICPC or even become a Red Coder, you can do it all here. 

Linux Department:

The **LINUX** Department of NJACK is the one which introduces you to the world of Linux and Open source Stuff. Linux is the world full of mysteries. The department helps you solve those mysteries. The Department conducts classes on basic linux commands for newbies, bash scripting and even advanced hacking. The main motive of the department is increase students' interest in linux.

**Comment by KokareIITP** [comment]
Edit this line : There is a virus in your computer and it is called windows. The LINUX Department of NJACK is the one which helps you to remove this virus from your system and introduce to the world of Linux and Open source Stuff. Linux is the world full of mysteries.

To : The LINUX Department of NJACK is the one which introduces you to the world of Linux and Open source Stuff. Linux is the world full of mysteries.

**Comment by chiragw15** [comment]
lol It was good
